---
services:
  mysqldb:
    image: sandhyakodamala/phpapp:db_img
    container_name: mydatabase
    ports:
      - 3308:3306
    networks:
      - mynetwork

  myapp:
    image: sandhyakodamala/phpapp:app_img
    container_name: myapp
    ports:
      - 1235:80
    networks:
      - mynetwork
    depends_on:
      - mysqldb

networks:
  mynetwork: 
    driver: bridge
