---
services:
  database:
    image: sandhyakodamala/phpapp:db_img
    container_name: mydatabase
    ports:
      - 3307:3306
    networks:
      - mynetwork

  myapp:
    image: sandhyakodamala/phpapp:app_img
    container_name: myapp
    ports:
      - 1234:80
    networks:
      - mynetwork
    depends_on:
      - database

networks:
  mynetwork: 
    - driver: bridge
